import type { NextPage } from 'next'
import Head from 'next/head'
import MainPage from '../components/pages/MainPage/MainPage'
import BaseHeader from '../components/organisms/BaseHeader/BaseHeader'
import BaseFooter from '../components/organisms/BaseFooter/BaseFooter'
import { footerLinks, headerLinks } from '../lib'
import { useEffect } from 'react'
import axios from 'axios'

const Home: NextPage = () => {
  useEffect(() => {
    ;(async () => {
      const { data } = await axios.get(
        `${process.env.NEXT_PUBLIC_MICRO_CMS_API_URL}/posts`,
        {
          headers: {
            'X-MICROCMS-API-KEY': `${process.env.NEXT_PUBLIC_MICRO_CMS_API_KEY}`,
          },
        }
      )
      console.log('data', data)
    })()
  }, [])
  return (
    <div>
      <Head>
        <title>Gullfoss</title>
        <meta name='description' content='Generated by create next app' />
      </Head>

      <main>
        <BaseHeader links={headerLinks} />
        <MainPage />
      </main>

      <BaseFooter links={footerLinks} />
    </div>
  )
}

export default Home
