import { NextPage } from 'next'
import CategoryPage from '../../components/pages/CategoryPage/CategoryPage'
import Head from 'next/head'
import BaseHeader from '../../components/organisms/BaseHeader/BaseHeader'
import { footerLinks, headerLinks } from '../../lib'
import BaseFooter from '../../components/organisms/BaseFooter/BaseFooter'

const slug: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Gullfoss</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <main>
        <BaseHeader links={headerLinks} />
        <CategoryPage />
      </main>
      <BaseFooter links={footerLinks} />
    </div>
  )
}

export default slug
