import {
  GetStaticPaths,
  GetStaticProps,
  InferGetStaticPropsType,
  NextPage,
} from 'next'
import CategoryPage from '../../components/pages/CategoryPage/CategoryPage'
import Head from 'next/head'
import BaseHeader from '../../components/organisms/BaseHeader/BaseHeader'
import { footerLinks, headerLinks } from '../../lib'
import BaseFooter from '../../components/organisms/BaseFooter/BaseFooter'
import { client } from '../../api'

const id: NextPage<Props> = ({ posts, tagName }) => {
  return (
    <div>
      <Head>
        <title>Gullfoss</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <main>
        <BaseHeader links={headerLinks} />
        <CategoryPage posts={posts} tagName={tagName} />
      </main>
      <BaseFooter links={footerLinks} />
    </div>
  )
}

export const getStaticPaths: GetStaticPaths = async () => {
  return {
    paths: [],
    fallback: 'blocking',
  }
}

export const getStaticProps: GetStaticProps = async (context) => {
  const id = context.params?.id
  const posts = await client.v1.posts.$get({
    query: { filters: `tags[contains]${encodeURI(String(id))}` },
  })

  const tags = posts.contents.map((content) => content.tags[0])
  const tagName = tags.find((tag) => tag.id === String(id))?.tag

  return {
    props: { posts, tagName },
    revalidate: 10,
  }
}

type Props = InferGetStaticPropsType<typeof getStaticProps>

export default id
