import { GetStaticPaths, NextPage } from 'next'
import Head from 'next/head'
import BaseHeader from '../../../components/organisms/BaseHeader/BaseHeader'
import { footerLinks, headerLinks } from '../../../lib'
import BaseFooter from '../../../components/organisms/BaseFooter/BaseFooter'
import SearchResultPage from '../../../components/pages/SearchResultPage/SearchResultPage'

const SearchPosts: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Gullfoss</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <main>
        <BaseHeader links={headerLinks} />
        <SearchResultPage />
      </main>
      <BaseFooter links={footerLinks} />
    </div>
  )
}

export default SearchPosts
