import { NextPage } from 'next'
import BaseHeader from '../../components/organisms/BaseHeader/BaseHeader'
import Head from 'next/head'
import { headerLinks } from '../../lib'

const Posts: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Gullfoss</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <BaseHeader links={headerLinks} />
      <p>Posts</p>
    </div>
  )
}

export default Posts
